version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kittens_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app/src  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=cats.settings
    command: >
      sh -c "sleep 10 &&
              python src/manage.py migrate &&
              python src/init_db.py &&  
              python src/manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
